package by.panasenko.webproject.controller.command;

public enum CommandName {
    GO_TO_ABOUT_PAGE_COMMAND,
    GO_TO_DIRECTION_PAGE_COMMAND,
    GO_TO_ERROR_PAGE_COMMAND,
    GO_TO_BASKET_PAGE_COMMAND,
    GO_TO_ITEM_PAGE_COMMAND,
    GO_TO_ADD_ITEM_PAGE_COMMAND,
    GO_TO_FLOWER_LIST_PAGE_COMMAND,
    GO_TO_CREATE_ADMIN_PAGE_COMMAND,
    GO_TO_ORDER_INFO_PAGE_COMMAND,
    GO_TO_MY_PROFILE_PAGE_COMMAND,
    GO_TO_LOGIN_PAGE_COMMAND,
    GO_TO_SUCCESS_PAGE_COMMAND,
    CHANGE_LOCALE_COMMAND,
    SIGN_IN_COMMAND
}
