package by.panasenko.webproject.command;

public enum CommandType {
    GO_TO_ABOUT_PAGE_COMMAND,
    GO_TO_DIRECTION_PAGE_COMMAND,
    GO_TO_ERROR_PAGE_COMMAND,
    GO_TO_BASKET_PAGE_COMMAND,
    GO_TO_ITEM_PAGE_COMMAND,
    GO_TO_ADD_ITEM_PAGE_COMMAND,
    GO_TO_FLOWER_LIST_PAGE_COMMAND,
    GO_TO_CREATE_ADMIN_PAGE_COMMAND,
    GO_TO_ORDER_INFO_PAGE_COMMAND,
    GO_TO_PROFILE_PAGE_COMMAND,
    GO_TO_LOGIN_PAGE_COMMAND,
    GO_TO_SUCCESS_PAGE_COMMAND,
    CHANGE_LOCALE_COMMAND,
    SIGN_IN_COMMAND,
    SIGN_UP_COMMAND,
    DEFAULT,
    FORGET_PASSWORD_COMMAND,
    LOG_OUT_COMMAND,
    PERSONAL_EDIT_COMMAND,
    FIND_PRODUCT_BY_CATEGORY_COMMAND,
    FLOWER_DETAIL_COMMAND,
    ADD_ITEM_TO_BASKET_COMMAND
}
